### ISSUE TITLE
Use of undefined constant CURLOPT_SSLVERSION - assumed 'CURLOPT_SSLVERSION'

### ISSUE THREAD

**Issue by gursel58** [kun391/yii2-paypal#7]
I have installed kin391/yii2-paypal in an Yii2 advanced template.
I have changed the two config files in kun391/yii2-paypal/lib 
I have added the following code in my controller
use kun391\paypal\ClassicAPI;
use kun391\paypal\RestAPI;

and in my payment action
    public function actionPayment()
    {
            echo '<pre/>';
            $params = [
                'email' => 'greg@urselconsulting.ca',
                'matchCriteria' => 'name',
                'firstName' => 'Greg',
                'lastName'  => 'Ursel'
                ];
            $params1 = [
                'currency' => 'USD', // only support currency same PayPal
                'description' => 'Buy some item',
                'total_price' => 470,
                'email' => 'greg@urselconsulting.ca',
                'items' => [
                    [
                        'name' => 'Vinamilk',
                        'quantity' => 2,
                        'price' => 100
                    ],
                    [
                        'name' => 'Pepsi',
                        'quantity' => 3,
                        'price' => 90
                    ]
                ]
            ];
            $response = Yii::$app->payPalClassic->getAccountInfo($params);
        //  $response = Yii::$app->payPalRest->getLinkCheckOut($params1);
            print_r($response);
            exit();
       return $this->render('payment');
    }

I have tried to use both payPalClassic->getAccountInfo and payPalRest->getLinkCheckOut and get the following error:
Use of undefined constant CURLOPT_SSLVERSION - assumed 'CURLOPT_SSLVERSION'
using either request.
Any thoughts on what I may have done wrong ?
Thanks
Greg

**Comment by gursel58** [comment]
Resolved the issue.
 php5-curl was not installed, installed it and reset Apache2 and everything is working now.

**Comment by kun391** [comment]
Okey, I will update Readme with requirements. Thanks @gursel58
