### ISSUE TITLE
PayPal\Exception\PayPalConnectionException handling a 400 Httpstatus

### ISSUE THREAD

**Issue by gursel58** [kun391/yii2-paypal#8]
I have successfully got all of the pieces working in order to do test transactions with PayPal. Now I am working on the exceptions and the first one I tried is an incorrect credit card number.
When I send in the transaction I get an error page:

PayPal\Exception\PayPalConnectionException
Got Http response code 400 when accessing https://api.sandbox.paypal.com/v1/payments/payment.

I have tried everything I can find on how to handle the exception so I can give the appropriate instructions to the user and get them to retry, but this error page always comes up.

Any ideas.
Thanks
Greg

**Comment by gursel58** [comment]
I did a little bit of digging into how PayPal handles its exceptions and found a few changes to RestAPI fixes the issue (not elegant yet still trying to find the right solution).

In RestAPI
- add
  use PayPal\Exception\PayPalConnectionException;

at the bottom of getLinkCheckOut
$error_code="0";
        $error_data=" ";
        try {
            $payment->create($this->config);
        } catch (PayPalConnectionException $ex) {
 //          throw new \DataErrorException($ex->getData(), $ex->getCode());+
//              Yii::warning($ex->getMessage());
            $error_code = $ex->getCode();
            $error_data = $ex->getData();
//          die($ex);
            } catch (Exception $ex){
              die ($ex);
            }
        // ### Get redirect url
        if ($error_code=='0') {
                $redirectUrl = $payment->getApprovalLink();
            }
        else
            {
                $redirectUrl = 'payment';
            }   

```
    return [
        'payment_id' => $payment->getId(),
        'status' => $payment->getState(),
        'redirect_url' => $redirectUrl,
        'description' => $transaction->getDescription(),
        'error_code' =>$error_code,
        'error_data' =>$error_data,
    ];
}
```

the addition of error_code and error_data allow the error information to be passed back to my controller action where I can filter out the user errors (bad card number, expiry dates etc) and have them reenter the information.
I will spend a little more time to refine. The one update that needs to be made in the original code is changing PPConnectionException to PayPalConnectionException.

Thanks
Greg

**Comment by kun391** [comment]
I was changed class PPConectionException to PayPalConnection
and some code for handle exception errors

Thanks @gursel58,
